Feat/api implementation
sidharthjain-zemoso/NodeJS-Assignments pull request #5
Opened 2024-05-15 07:33 UTC by sidharthjain-zemoso

Description:
1. Implemented candidate and user APIs for checkr.
2. Performed validation using zod and did error handling as well.
3. Added stateless authentication using tokens. Used jsonwebtokens package for token generation and validation.
4. Used bcryptjs to hash passwords.
5. As part of learning explored cron jobs to send email when pre-adverse action is performed.

2024-05-15 10:58 UTC, akshayvijayjain requested changes

2024-05-15 10:58 UTC, akshayvijayjain commented on checkr/src/routes/candidate.ts
> +router.post("/:candidateId/actions/engage", isAuth, candidateValidators.engageCandidate, tryCatch(candidateController.engageCandidate));
this post request should be converted in put request, as per http standard, since we are only modifying the status.

Please let me know your views

2024-05-15 10:58 UTC, akshayvijayjain commented on checkr/src/routes/candidate.ts
> +router.get("/list", isAuth, candidateValidators.getCandidates, tryCatch(candidateController.getCandidates));
api names have to be improved

CandidateRouter.get('/:id', tryCatch(CandidateController.getCandidate));
CandidateRouter.get('/', tryCatch(CandidateController.listCandidates));
CandidateRouter.post('/', tryCatch(CandidateController.createCandidate));

2024-05-15 10:58 UTC, akshayvijayjain commented on checkr/src/routes/user.ts
> +router.post("/get-user-details/:userId", userValidators.getUserDataById, isAuth, tryCatch(userController.getUserDataById));
api names need improvement for /get-user-details

it should be get request 
it should just have "/:userId"

Please let me know your views

2024-05-15 11:39 UTC, sidharthjain-zemoso commented on checkr/src/routes/candidate.ts
> +router.post("/:candidateId/actions/engage", isAuth, candidateValidators.engageCandidate, tryCatch(candidateController.engageCandidate));
Yes. Will update.

2024-05-15 11:40 UTC, sidharthjain-zemoso commented on checkr/src/routes/user.ts
> +router.post("/get-user-details/:userId", userValidators.getUserDataById, isAuth, tryCatch(userController.getUserDataById));
Yes. It is supposed to be get request.

2024-05-15 11:40 UTC, sidharthjain-zemoso commented on checkr/src/routes/candidate.ts
> +router.get("/list", isAuth, candidateValidators.getCandidates, tryCatch(candidateController.getCandidates));
Sure. Will update.

2024-05-15 12:03 UTC, sidharthjain-zemoso commented on checkr/src/routes/candidate.ts
> +router.get("/list", isAuth, candidateValidators.getCandidates, tryCatch(candidateController.getCandidates));
Updated getCandidates to getCandidateList.

2024-05-16 09:50 UTC, akshayvijayjain commented on checkr/src/routes/candidate.ts
> +router.get("/list", isAuth, candidateValidators.getCandidates, tryCatch(candidateController.getCandidates));
yes, your function naming is better!

I was concerned about route

2024-05-16 09:52 UTC, akshayvijayjain commented
this looks good, creating pending issues
1. when user already exists, we should throw error with appropriate status code
2. when there is error to be returned return it with appropriate code
3. thus status code should be part of all the response

2024-05-16 09:53 UTC, akshayvijayjain approved these changes

2024-05-16 10:08 UTC, merged