Feat/unit test
sidharthjain-zemoso/NodeJS-Assignments pull request #6
Opened 2024-05-16 04:54 UTC by sidharthjain-zemoso

2024-05-16 10:01 UTC, akshayvijayjain requested changes

2024-05-16 10:01 UTC, akshayvijayjain commented on checkr/test/middlewares/auth.ts
please name test files, as ending with .spec.ts or .test.ts

2024-05-16 10:01 UTC, akshayvijayjain commented on checkr/src/services/candidate.ts
> +            if (error instanceof CustomError) {
think how you can move this logic to CustomError Class

2024-05-16 19:10 UTC, sidharthjain-zemoso commented on checkr/src/services/candidate.ts
> +            if (error instanceof CustomError) {
Here, we are throwing customError with some message in try block and in catch block we earlier were throwing again a custom error with another message which overrides the previous custom error message. To handle that we have this logic. 
Now, to move this logic to Custom Error class, should we pass error as constructor argument and then check if it is instance of custom error @akshayvijayjain ?

2024-05-16 19:10 UTC, sidharthjain-zemoso commented on checkr/test/middlewares/auth.ts
Done

2024-05-17 11:48 UTC, akshayvijayjain commented on checkr/src/common/interfaces/custom-error.ts
> +            super(error.message);
I feel, you can throw from constructor, if error is already instance of CustomError.

thus we avoid created nested CustomError.

yes, this is what I was referring in my previous comment

2024-05-17 11:50 UTC, akshayvijayjain approved these changes

2024-05-17 12:43 UTC, merged